version: 0.2

phases:
  install:
    commands:
      - npm i -g npm
      - npm i
  build:
    commands:
      - npm run build
      - npm run cdk -- synth

artifacts:
  base-directory: cdk.out
  files:
    - "**/*"
